[package]
name = "quork"
version = "0.1.1"
license = "MIT"
description = "A collection of small things that don't deserve their own crate"
keywords = ["admin", "sys"]
authors = ["Juliette Cordor"]
documentation = "https://docs.rs/quork"
repository = "https://github.com/jewlexx/quork.git"
homepage = "https://github.com/jewlexx/quork.git"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["quork-proc"]

[dependencies]
cfg-if = "1.0.0"
quork-proc = { version = "0.1.0", path = "quork-proc" }

[target.'cfg(not(windows))'.dependencies]
nix = "0.24.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["everything"] }
