[package]
name = "is-admin"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/jewlexx/is-admin.git"
homepage = "https://github.com/jewlexx/is-admin.git"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "1.0.73"
