[package]
name = "quork"
version = "0.1.0"
license = "MIT"
description = "A collection of small things that make interacting with the system easier"
keywords = ["admin", "sys"]
authors = ["Juliette Cordor"]
documentation = "https://docs.rs/is-admin"
repository = "https://github.com/jewlexx/is-admin.git"
homepage = "https://github.com/jewlexx/is-admin.git"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["quork-proc"]

[dependencies]
cfg-if = "1.0.0"
nix = "0.24.1"

[build-dependencies]
cc = "1.0.73"

[target.'cfg(target_os = "windows")'.dependencies]
windows-api = { package = "windows", version = "0.37.0", features = ["Networking", "Networking_Connectivity", "Win32_NetworkManagement_NetManagement"] }
