[package]
name = "quork"
version = "0.1.1"
license = "MIT"
description = "A collection of small things that don't deserve their own crate"
keywords = ["admin", "sys"]
authors = ["Juliette Cordor"]
documentation = "https://docs.rs/is-admin"
repository = "https://github.com/jewlexx/is-admin.git"
homepage = "https://github.com/jewlexx/is-admin.git"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["quork-proc"]

[dependencies]
cfg-if = "1.0.0"
cxx = "1.0.72"
quork-proc = { version = "0.1.0", path = "quork-proc" }

[build-dependencies]
cc = "1.0.73"

[target.'cfg(not(windows))'.dependencies]
nix = "0.24.1"
